### ISSUE TITLE
Consider PyCharm as alternative to Anaconda

### ISSUE THREAD

**Issue by tla** [djbpitt/collatexInstallation#5]
...because then there's no need to muck about on the command line. CollateX and Levenshtein can be installed directly from the IDE.

**Comment by djbpitt** [comment]
Free educational version or free educational license for professional version? I have both, but haven't played with them enough to be able to tell whether there are differences we would care about. Free educational version is probably easier because you don't need to register for a free student license; it just works.

**Comment by tla** [comment]
It turns out that PyCharm isn't so much an alternative as an add-on - the IDE can use either the Anaconda distro or the standard Python one, but needs to have some form of Python installed already. I'm trying it out on two Windows VMs, one with the community edition and one with the professional, to see if there is any difference that matters. So far there doesn't seem to be.

At any rate Anaconda@Python3.4 has the massive advantage that python-Levenshtein can be installed from pip, since they package a compiler with the distribution. In light of all my poking around I'm less inclined to push PyCharm on the workshop participants than I thought I would be, since all it really gains them is the ability to install packages without running pip from the command line.

**Comment by djbpitt** [comment]
The advantage of installing packages without running pip from the command line is offset by needing to tell PyCharm which version of Python to use. That isn't hard, but it doesn't seem worth the effort unless we're strongly committed to the PyCharm development environment. I'm inclined to suggest that 1) we recommend Anaconda and 2) we not say anything about PyCharm. If that's okay with you, we can close this issue.

**Comment by tla** [comment]
Sure, that's the conclusion I was coming to.
