### ISSUE TITLE
md ~ html

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/collatexInstallation#6]
@tla Instead of maintaining parallel html and md versions of the documentation, we should probably merge them, so that we don't wind up with two sets of instructions that are similar but out of sync. How would you like us to proceed?

**Comment by tla** [comment]
I generated the md version basically for my own editing convenience, and so I didn't stomp on the HTML version that already existed.

What we could do is to regenerate the HTML from the markdown via pandoc - that way there is a version directly viewable and editable on Github, and one with your CSS settings for (I presume) your teaching site. (We could also generate the markdown from the HTML of course, though I find md easier to edit.)

**Comment by djbpitt** [comment]
Dear Tara,

I'm fine with stomping on the HTML; it's a version, and now an out of date
one, so we should retain whatever we find useful and get rid of the rest.
Let's ignore the HTML for now and work with just the markdown, since you've
started that. As you suggest, we can generate HTML from the markdown later,
as needed.

Best,

David

**Comment by tla** [comment]
OK!
