### ISSUE TITLE
Editing the instructions

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/collatexInstallation#7]
@tla If I'm correct in thinking that markdown doesn't support commenting out blocks of text, how should we manage the collaborative editing? I've just installed Anaconda on MacOS and was about to update that part of the instructions in the md file, but I need to ask first whether you're comfortable with our both editing the same file in an environment where we can't comment anything out (which means that a deletion is really a deletion).

**Comment by tla** [comment]
As far as I can see, you can use HTML comment syntax in Markdown - a quick test suggests that it works fine. Is that adequate?

**Comment by djbpitt** [comment]
Yep. Thanks!
